# generated by datamodel-codegen:
#   filename:  openapi_snapshot.json

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel


class AcceptInvitation(BaseModel):
    email: EmailStr = Field(..., title="Email")
    invitation_key: str = Field(..., title="Invitation Key")


class AgeBias(BaseModel):
    bias_type: Literal["AGE"] = Field("AGE", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class AirGappedBody(BaseModel):
    email: str = Field(..., title="Email")
    password: str = Field(..., title="Password")


class AllBias(BaseModel):
    bias_type: Literal["ALL"] = Field("ALL", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class ApiKeyKind(str, Enum):
    STANDARD = "STANDARD"
    CI = "CI"


class AugmentationName(str, Enum):
    RANDOM_HORIZONTAL_FLIP = "RandomHorizontalFlip"
    RANDOM_VERTICAL_FLIP = "RandomVerticalFlip"
    RANDOM_ROTATION = "RandomRotation"
    RANDOM_PERSPECTIVE = "RandomPerspective"
    GAUSSIAN_NOISE = "GaussianNoise"
    RANDOM_GRAYSCALE = "RandomGrayscale"
    GAUSSIAN_BLUR = "GaussianBlur"
    ADD_GAUSSIAN_NOISE = "AddGaussianNoise"
    MASK_FEATURES = "MaskFeatures"


class BiasType(str, Enum):
    ALL = "ALL"
    RACE = "RACE"
    NATIONALITY = "NATIONALITY"
    GENDER = "GENDER"
    PHYSICAL_APPEARANCE = "PHYSICAL_APPEARANCE"
    RELIGION = "RELIGION"
    AGE = "AGE"


class COCO(BaseModel):
    json_url: str = Field(..., title="Json Url")
    type: Literal["COCO"] = Field("COCO", title="Type")


class CatalogSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inspect_ai: str = Field(..., title="Inspect Ai")
    inspect_evals: str = Field(..., title="Inspect Evals")


class ImgSize(RootModel[tuple[int, int]]):
    root: tuple[int, int] = Field(..., max_length=2, min_length=2, title="Img Size")


class ClassificationRunArgs(BaseModel):
    img_size: ImgSize | None = Field(None, title="Img Size")
    upsample: bool | None = Field(None, title="Upsample")


class CreateHuggingFaceToken(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    token: str = Field(..., min_length=1, title="Token")


class CreateModel(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    id: int = Field(..., title="Id")
    message: str = Field(..., title="Message")
    updated_at: datetime = Field(..., title="Updated At")


class CreateOrganization(BaseModel):
    description: str | None = Field(None, examples=[None], title="Description")
    name: str = Field(..., examples=["Organization 1"], title="Name")
    parent_id: int | None = Field(None, examples=[None], title="Parent Id")


class CreateStorageGit(BaseModel):
    branch: str = Field(..., title="Branch")
    repo_id: int = Field(..., title="Repo Id")


class DatasetSplit(str, Enum):
    FORGET = "FORGET"
    RETAIN = "RETAIN"
    TEST = "TEST"


class DatasetType(str, Enum):
    NORMAL = "normal"
    BIAS = "bias"
    UNBIAS = "unbias"


class DefenseHallucinationBehavior(BaseModel):
    hallucination_type: Literal["DEFENSE"] = Field(
        "DEFENSE", title="Hallucination Type"
    )
    type: Literal["HALLUCINATION"] = Field("HALLUCINATION", title="Type")


class DisplayApiKey(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    expired: bool = Field(..., title="Expired")
    expires_soon: bool = Field(..., title="Expires Soon")
    id: int = Field(..., title="Id")
    kind: ApiKeyKind = ApiKeyKind.STANDARD
    name: str = Field(..., min_length=1, title="Name")
    revoked: bool = Field(..., title="Revoked")
    updated_at: datetime = Field(..., title="Updated At")
    user_owner_id: int = Field(..., title="User Owner Id")


class SampleLimit(RootModel[int]):
    root: int = Field(..., gt=0, title="Sample Limit")


class TaskId(RootModel[str]):
    root: str = Field(..., pattern="^inspect_evals/[A-Za-z0-9_]+$")


class ExternalEvalRunInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model_id: int | None = Field(None, title="Model Id")
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    sample_limit: SampleLimit | None = Field(None, title="Sample Limit")
    source_run_id: str | None = Field(None, title="Source Run Id")
    task_ids: list[TaskId] = Field(..., min_length=1, title="Task Ids")


class GenderBias(BaseModel):
    bias_type: Literal["GENDER"] = Field("GENDER", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class GeneralHallucinationBehavior(BaseModel):
    hallucination_type: Literal["GENERAL"] = Field(
        "GENERAL", title="Hallucination Type"
    )
    type: Literal["HALLUCINATION"] = Field("HALLUCINATION", title="Type")


class GitPlainAuth(BaseModel):
    id: int | None = Field(None, title="Id")
    password: str = Field(..., title="Password")
    username: str = Field(..., title="Username")


class GitPlainAuthBase(BaseModel):
    password: str = Field(..., title="Password")
    username: str = Field(..., title="Username")


class GitRepoOut(BaseModel):
    auth_type: str = Field(..., title="Auth Type")
    created_at: datetime = Field(..., title="Created At")
    id: int = Field(..., title="Id")
    name: str = Field(..., title="Name")
    repository_url: str = Field(..., title="Repository Url")
    updated_at: datetime = Field(..., title="Updated At")


class GitSSHAuthBase(BaseModel):
    ssh_key: str = Field(..., title="Ssh Key")
    ssh_password: str | None = Field(..., title="Ssh Password")


class HirundoCSV(BaseModel):
    csv_url: str = Field(..., title="Csv Url")
    type: Literal["HirundoCSV"] = Field("HirundoCSV", title="Type")


class HirundoCSVDataset(BaseModel):
    csv_url: str = Field(..., title="Csv Url")
    type: Literal["HirundoCSV"] = Field("HirundoCSV", title="Type")


class HuggingFaceAudio(BaseModel):
    audio_column: str = Field(..., title="Audio Column")
    config_name: str | None = Field(None, title="Config Name")
    data_dir: str | None = Field(None, title="Data Dir")
    data_files: str | None = Field(None, title="Data Files")
    split: str | None = Field(None, title="Split")
    text_column: str = Field(..., title="Text Column")
    type: Literal["HuggingFaceAudio"] = Field("HuggingFaceAudio", title="Type")


class HuggingFaceAuthType(str, Enum):
    NONE = "none"
    TOKEN = "token"


class HuggingFaceDataset(BaseModel):
    hugging_face_dataset_name: str = Field(..., title="Hugging Face Dataset Name")
    token: str | None = Field(None, title="Token")
    token_id: int | None = Field(None, title="Token Id")
    type: Literal["HuggingFaceDataset"] = Field("HuggingFaceDataset", title="Type")


class HuggingFaceTokenOut(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    creator_id: int = Field(..., title="Creator Id")
    creator_name: str = Field(..., title="Creator Name")
    id: int = Field(..., title="Id")
    name: str = Field(..., max_length=255, min_length=1, title="Name")
    organization_id: int = Field(..., title="Organization Id")
    token_preview: str = Field(..., title="Token Preview")
    updated_at: datetime = Field(..., title="Updated At")


class ImageAugmentationName(str, Enum):
    RANDOM_HORIZONTAL_FLIP = "RandomHorizontalFlip"
    RANDOM_VERTICAL_FLIP = "RandomVerticalFlip"
    RANDOM_ROTATION = "RandomRotation"
    RANDOM_PERSPECTIVE = "RandomPerspective"
    GAUSSIAN_NOISE = "GaussianNoise"
    RANDOM_GRAYSCALE = "RandomGrayscale"
    GAUSSIAN_BLUR = "GaussianBlur"


class InferredModelParameterCountRequest(BaseModel):
    organization_id: int | None = Field(None, title="Organization Id")
    path_or_repo_id: str = Field(..., title="Path Or Repo Id")
    token: str | None = Field(None, title="Token")
    token_id: int | None = Field(None, title="Token Id")


class InferredModelParameterCountResponse(BaseModel):
    parameter_count: int | None = Field(..., title="Parameter Count")


class JudgeModel(BaseModel):
    batch_size: int | None = Field(None, title="Batch Size")
    output_tokens: int | None = Field(None, title="Output Tokens")
    path_or_repo_id: str = Field(..., title="Path Or Repo Id")
    token: str | None = Field(None, title="Token")
    token_id: int | None = Field(None, title="Token Id")
    use_4bit: bool | None = Field(None, title="Use 4Bit")


class KeylabsAuth(BaseModel):
    instance: str = Field(..., title="Instance")
    password: str = Field(..., title="Password")
    username: str = Field(..., title="Username")


class KeylabsObjDetImages(BaseModel):
    keylabs_auth: KeylabsAuth | None = None
    labels_dir_url: str = Field(..., title="Labels Dir Url")
    project_id: str = Field(..., title="Project Id")
    project_name: str | None = Field(None, title="Project Name")
    type: Literal["KeylabsObjDetImages"] = Field("KeylabsObjDetImages", title="Type")
    with_attributes: bool = Field(True, title="With Attributes")


class KeylabsObjDetVideo(BaseModel):
    keylabs_auth: KeylabsAuth | None = None
    labels_dir_url: str = Field(..., title="Labels Dir Url")
    project_id: str = Field(..., title="Project Id")
    project_name: str | None = Field(None, title="Project Name")
    type: Literal["KeylabsObjDetVideo"] = Field("KeylabsObjDetVideo", title="Type")
    with_attributes: bool = Field(True, title="With Attributes")


class KeylabsObjSegImages(BaseModel):
    keylabs_auth: KeylabsAuth | None = None
    labels_dir_url: str = Field(..., title="Labels Dir Url")
    project_id: str = Field(..., title="Project Id")
    project_name: str | None = Field(None, title="Project Name")
    type: Literal["KeylabsObjSegImages"] = Field("KeylabsObjSegImages", title="Type")
    with_attributes: bool = Field(True, title="With Attributes")


class KeylabsObjSegVideo(BaseModel):
    keylabs_auth: KeylabsAuth | None = None
    labels_dir_url: str = Field(..., title="Labels Dir Url")
    project_id: str = Field(..., title="Project Id")
    project_name: str | None = Field(None, title="Project Name")
    type: Literal["KeylabsObjSegVideo"] = Field("KeylabsObjSegVideo", title="Type")
    with_attributes: bool = Field(True, title="With Attributes")


class LabelStudioConfigResponse(BaseModel):
    base_url: str | None = Field(None, title="Base Url")
    enabled: bool = Field(..., title="Enabled")


class LabelStudioLoginRequest(BaseModel):
    redirect_path: str | None = Field(None, title="Redirect Path")


class LabelingType(str, Enum):
    SINGLE_LABEL_CLASSIFICATION = "SingleLabelClassification"
    OBJECT_DETECTION = "ObjectDetection"
    OBJECT_SEGMENTATION = "ObjectSegmentation"
    SEMANTIC_SEGMENTATION = "SemanticSegmentation"
    PANOPTIC_SEGMENTATION = "PanopticSegmentation"
    SPEECH_TO_TEXT = "SpeechToText"


class LaunchRunResponse(BaseModel):
    message: str = Field(..., title="Message")
    run_id: str = Field(..., title="Run Id")


class LaunchRunWithNameResponse(BaseModel):
    message: str = Field(..., title="Message")
    name: str = Field(..., title="Name")
    run_id: str = Field(..., title="Run Id")


class LegalHallucinationBehavior(BaseModel):
    hallucination_type: Literal["LEGAL"] = Field("LEGAL", title="Hallucination Type")
    type: Literal["HALLUCINATION"] = Field("HALLUCINATION", title="Type")


class LicenseRequiredResponse(BaseModel):
    detail: str = Field(..., title="Detail")


class LlmSourceType(str, Enum):
    HUGGINGFACE_TRANSFORMERS = "huggingface_transformers"
    LOCAL_TRANSFORMERS = "local_transformers"


class ParameterCount(RootModel[int]):
    root: int = Field(..., gt=0, title="Parameter Count")


class LocalTransformersModel(BaseModel):
    code_revision: str | None = Field(None, title="Code Revision")
    local_path: str = Field(..., title="Local Path")
    parameter_count: ParameterCount | None = Field(None, title="Parameter Count")
    revision: str | None = Field(None, title="Revision")
    trust_remote_code: bool = Field(True, title="Trust Remote Code")
    type: Literal["local_transformers"] = Field("local_transformers", title="Type")


class LoginBody(BaseModel):
    id_token: str = Field(..., title="Id Token")


class ClassWeightingEnum(str, Enum):
    UNIFORM = "uniform"
    BALANCED = "balanced"
    LOG_BALANCED = "log_balanced"


class ClassWeighting(RootModel[ClassWeightingEnum | None]):
    root: ClassWeightingEnum | None = Field(None, title="Class Weighting")


class Kwargs(str, Enum):
    NONE = "none"
    MEAN = "mean"
    SUM = "sum"


class LossFunction(BaseModel):
    class_weighting: ClassWeighting | None = Field(None, title="Class Weighting")
    kwargs: dict[str, int | float | bool | Kwargs] | None = Field(None, title="Kwargs")
    name: str | None = Field(None, title="Name")


class LrFinderParams(BaseModel):
    active: bool | None = Field(None, title="Active")
    max_lr: float | None = Field(None, title="Max Lr")
    min_lr: float | None = Field(None, title="Min Lr")
    number_of_training_steps: int | None = Field(None, title="Number Of Training Steps")


class LrScheduler(BaseModel):
    kwargs: dict[str, float | list[float]] | None = Field(None, title="Kwargs")
    name: str | None = Field(None, title="Name")


class MedicalHallucinationBehavior(BaseModel):
    hallucination_type: Literal["MEDICAL"] = Field(
        "MEDICAL", title="Hallucination Type"
    )
    type: Literal["HALLUCINATION"] = Field("HALLUCINATION", title="Type")


class MessageResponse(BaseModel):
    message: str = Field(..., title="Message")


class Metadata(BaseModel):
    organization_id: int = Field(
        ...,
        description="The ID of the organization who owns the object",
        title="Organization Id",
    )


class ModalityType(str, Enum):
    RADAR = "RADAR"
    VISION = "VISION"
    SPEECH = "SPEECH"
    TABULAR = "TABULAR"
    MULTIMODAL = "MULTIMODAL"
    TIMESERIES = "TIMESERIES"


class ModelSourceType(str, Enum):
    PYTORCH_RAW_PTH = "pytorch_raw_pth"
    TORCHVISION = "torchvision"


class ModifyGitRepo(BaseModel):
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    plain_auth: GitPlainAuthBase | None
    repository_url: str | None = Field(..., title="Repository Url")
    ssh_auth: GitSSHAuthBase | None


class ModifyOrganization(BaseModel):
    description: str | None = Field(None, title="Description")
    name: str | None = Field(None, title="Name")


class MultimodalModalityType(str, Enum):
    VISION = "VISION"
    RADAR = "RADAR"
    TABULAR = "TABULAR"
    TIMESERIES = "TIMESERIES"


class NationalityBias(BaseModel):
    bias_type: Literal["NATIONALITY"] = Field("NATIONALITY", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class NewApiKeyResponse(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    id: int = Field(..., title="Id")
    key_value: str = Field(..., title="Key Value")
    kind: ApiKeyKind = ApiKeyKind.STANDARD
    name: str = Field(..., min_length=1, title="Name")
    updated_at: datetime = Field(..., title="Updated At")
    user_owner_id: int = Field(..., title="User Owner Id")


class ObjectDetectionRunArgs(BaseModel):
    add_mask_channel: bool | None = Field(None, title="Add Mask Channel")
    crop_ratio: float | None = Field(1.0, title="Crop Ratio")
    img_size: ImgSize | None = Field(None, title="Img Size")
    min_abs_bbox_area: int | None = Field(None, title="Min Abs Bbox Area")
    min_abs_bbox_size: int | None = Field(None, title="Min Abs Bbox Size")
    min_rel_bbox_area: float | None = Field(None, title="Min Rel Bbox Area")
    min_rel_bbox_size: float | None = Field(None, title="Min Rel Bbox Size")
    upsample: bool | None = Field(None, title="Upsample")


class OptimizerParams(BaseModel):
    kwargs: dict[str, int | float] | None = Field(None, title="Kwargs")
    name: str | None = Field(None, title="Name")


class OrganizationOut(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    description: str | None = Field(None, title="Description")
    id: int = Field(..., title="Id")
    name: str = Field(..., title="Name")
    owner_id: int | None = Field(None, title="Owner Id")
    parent_id: int | None = Field(None, title="Parent Id")
    updated_at: datetime = Field(..., title="Updated At")


class PhysicalAppearanceBias(BaseModel):
    bias_type: Literal["PHYSICAL_APPEARANCE"] = Field(
        "PHYSICAL_APPEARANCE", title="Bias Type"
    )
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class PresetType(str, Enum):
    BBQ_BIAS = "BBQ_BIAS"
    BBQ_UNBIAS = "BBQ_UNBIAS"
    UNQOVER_BIAS = "UNQOVER_BIAS"
    HALU_EVAL = "HALU_EVAL"
    MED_HALLU = "MED_HALLU"
    INJECTION_EVAL = "INJECTION_EVAL"
    XSTEST = "XSTEST"
    OR_BENCH = "OR_BENCH"


class PaperUrl(RootModel[AnyUrl]):
    root: AnyUrl = Field(..., title="Paper Url")


class PublicCatalogTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., pattern="^inspect_evals/[A-Za-z0-9_]+$", title="Id")
    name: str = Field(..., title="Name")
    sample_count: int | None = Field(..., title="Sample Count")


class PyTorchRawPthModel(BaseModel):
    code_url: str = Field(..., title="Code Url")
    raw_pth_url: str = Field(..., title="Raw Pth Url")
    type: Literal["pytorch_raw_pth"] = Field("pytorch_raw_pth", title="Type")


class RaceBias(BaseModel):
    bias_type: Literal["RACE"] = Field("RACE", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class RefusalBehavior(BaseModel):
    type: Literal["REFUSAL"] = Field("REFUSAL", title="Type")


class ReligionBias(BaseModel):
    bias_type: Literal["RELIGION"] = Field("RELIGION", title="Bias Type")
    type: Literal["BIAS"] = Field("BIAS", title="Type")


class RenameEvalRun(BaseModel):
    new_name: str = Field(..., title="New Name")


class RenameRun(BaseModel):
    new_name: str = Field(..., title="New Name")


class ResultDownloadError(BaseModel):
    detail: str = Field(..., title="Detail")


class Role(str, Enum):
    OWNER = "owner"
    ADMIN = "admin"
    USER = "user"


class ScenarioType(str, Enum):
    RANDOM_SAMPLES = "RANDOM_SAMPLES"
    CLASS_SUBSET = "CLASS_SUBSET"
    FULL_CLASS = "FULL_CLASS"
    UNSET = "UNSET"


class SecurityBehavior(BaseModel):
    type: Literal["SECURITY"] = Field("SECURITY", title="Type")


class SetPrimaryOrganization(BaseModel):
    user_association_id: int = Field(..., examples=[1], title="User Association Id")


class StorageAzureBase(BaseModel):
    account_url: str = Field(
        ...,
        description="See https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#create-the-client for how to create this URL",
        title="Account Url",
    )
    container_name: str = Field(..., title="Container Name")
    credential_json: dict[str, Any] | None = Field(..., title="Credential Json")
    tenant_id: str | None = Field(..., title="Tenant Id")


class StorageAzureOut(BaseModel):
    account_url: str = Field(..., title="Account Url")
    container: str = Field(..., title="Container")
    id: int = Field(..., title="Id")


class StorageGCPBase(BaseModel):
    bucket_name: str = Field(..., title="Bucket Name")
    credentials_json: dict[str, Any] | None = Field(None, title="Credentials Json")
    project: str = Field(..., title="Project")


class StorageGCPOut(BaseModel):
    bucket_name: str = Field(..., title="Bucket Name")
    id: int = Field(..., title="Id")
    project: str = Field(..., title="Project")


class StorageGitOut(BaseModel):
    branch: str = Field(..., title="Branch")
    id: int = Field(..., title="Id")
    repo: GitRepoOut


class StorageHuggingFaceBase(BaseModel):
    branch: str | None = Field(None, title="Branch")
    dataset_id: str | None = Field(None, title="Dataset Id")
    model_id: str | None = Field(None, title="Model Id")
    token: str | None = Field(None, title="Token")
    token_id: int | None = Field(None, title="Token Id")


class StorageHuggingFaceOut(BaseModel):
    auth_type: HuggingFaceAuthType
    branch: str | None = Field(..., title="Branch")
    dataset_id: str | None = Field(..., title="Dataset Id")
    id: int = Field(..., title="Id")
    model_id: str | None = Field(..., title="Model Id")
    token_id: int | None = Field(..., title="Token Id")


class StorageS3Base(BaseModel):
    access_key_id: str | None = Field(..., title="Access Key Id")
    bucket_url: str = Field(..., title="Bucket Url")
    endpoint_url: str | None = Field(..., title="Endpoint Url")
    region_name: str = Field(..., title="Region Name")
    secret_access_key: str | None = Field(..., title="Secret Access Key")


class StorageS3Out(BaseModel):
    access_key_id: str | None = Field(..., title="Access Key Id")
    bucket_url: str = Field(
        ...,
        max_length=1023,
        min_length=8,
        pattern="s3?://[a-z0-9.-]{3,64}[/]?",
        title="Bucket Url",
    )
    endpoint_url: str | None = Field(..., title="Endpoint Url")
    id: int = Field(..., title="Id")
    region_name: str = Field(..., title="Region Name")


class StorageTypes(str, Enum):
    S3 = "S3"
    GCP = "GCP"
    AZURE = "Azure"
    GIT = "Git"
    LOCAL = "Local"
    HUGGING_FACE = "HuggingFace"


class TabAugmentationName(str, Enum):
    ADD_GAUSSIAN_NOISE = "AddGaussianNoise"
    MASK_FEATURES = "MaskFeatures"


class TorchVisionModel(BaseModel):
    model_name: str = Field(..., title="Model Name")
    safetensors_weights_url: str = Field(..., title="Safetensors Weights Url")
    type: ModelSourceType = ModelSourceType.TORCHVISION


class TrainerParams(BaseModel):
    auto_find_batch_size: bool | None = Field(None, title="Auto Find Batch Size")
    batch_size: int | None = Field(None, title="Batch Size")
    loss_function: LossFunction | None = None
    lr_finder: LrFinderParams | None = None
    lr_scheduler: LrScheduler | None = None
    max_epochs: int | None = Field(None, title="Max Epochs")
    optimizer: OptimizerParams | None = None
    patience: int | None = Field(None, title="Patience")


class TransferOwnershipInfo(BaseModel):
    organization_id: int = Field(..., title="Organization Id")
    target_owner_id: int = Field(..., title="Target Owner Id")


class ImageSize(RootModel[tuple[int, int]]):
    root: tuple[int, int] = Field(..., max_length=2, min_length=2, title="Image Size")


class UnlearningLlmAdvancedOptions(BaseModel):
    max_tokens_for_model: dict[DatasetType, int] | int | None = Field(
        None, title="Max Tokens For Model"
    )


class Name(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1, title="Name")


class Token(RootModel[str]):
    root: str = Field(..., min_length=1, title="Token")


class UpdateHuggingFaceToken(BaseModel):
    name: Name | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    token: Token | None = Field(None, title="Token")


class UserOut(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    full_name: str = Field(..., title="Full Name")
    id: int = Field(..., title="Id")
    primary_organization_id: int | None = Field(None, title="Primary Organization Id")
    updated_at: datetime = Field(..., title="Updated At")
    username: str = Field(..., title="Username")


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title="Context")
    input: Any | None = Field(None, title="Input")
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class WorkOSLogoutResponse(BaseModel):
    logoutUrl: str = Field(..., title="Logouturl")


class WorkOSMessageResponse(BaseModel):
    message: str = Field(..., title="Message")


class WorkOSSessionResponse(BaseModel):
    full_name: str = Field(..., title="Full Name")
    message: str = Field(..., title="Message")
    primary_organization_id: int = Field(..., title="Primary Organization Id")
    primary_organization_name: str = Field(..., title="Primary Organization Name")
    primary_role: Role
    user_id: int = Field(..., title="User Id")
    username: str = Field(..., title="Username")


class YOLO(BaseModel):
    data_yaml_url: str | None = Field(None, title="Data Yaml Url")
    labels_dir_url: str = Field(..., title="Labels Dir Url")
    type: Literal["YOLO"] = Field("YOLO", title="Type")


class ServerDatasetQaModelsRunRunInfo(BaseModel):
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    run_args: ClassificationRunArgs | ObjectDetectionRunArgs = Field(
        ..., title="Run Args"
    )


class ServerUnlearningLlmModelsEvalRunInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bias_type: BiasType | None = None
    judge_model: JudgeModel | None = None
    model_id: int | None = Field(None, title="Model Id")
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    preset_type: PresetType
    source_run_id: str | None = Field(None, title="Source Run Id")


class Aggressiveness(RootModel[float]):
    root: float = Field(..., gt=0.0, le=1.0, multiple_of=0.001, title="Aggressiveness")


class ApiKeyBase(BaseModel):
    kind: ApiKeyKind = ApiKeyKind.STANDARD
    name: str = Field(..., min_length=1, title="Name")


class ApiResponse(BaseModel):
    api_key: NewApiKeyResponse
    message: str = Field(..., title="Message")


class AugmentationParams(BaseModel):
    kwargs: dict[str, int | float] | None = Field(None, title="Kwargs")
    name: ImageAugmentationName


class CreateGitRepo(BaseModel):
    name: str = Field(..., title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    plain_auth: GitPlainAuthBase | None = Field(
        ..., examples=[None, {"password": "password", "username": "ben"}]
    )
    replace_if_exists: bool = Field(False, title="Replace If Exists")
    repository_url: str = Field(..., title="Repository Url")
    ssh_auth: GitSSHAuthBase | None = Field(
        ...,
        examples=[
            {
                "ssh_key": "SOME_PRIVATE_SSH_KEY",
                "ssh_password": "SOME_SSH_KEY_PASSWORD",
            },
            None,
        ],
    )


class CreateInvitation(BaseModel):
    emails: list[EmailStr] = Field(..., title="Emails")
    invitation_key: str | None = Field(None, title="Invitation Key")
    organization_id: int = Field(..., title="Organization Id")
    role: Role = Role.USER


class CreateStorageConfig(BaseModel):
    azure: StorageAzureBase | None = Field(None, examples=[None, None])
    gcp: StorageGCPBase | None = Field(None, examples=[None, None])
    git: CreateStorageGit | None = Field(None, examples=[None, None])
    huggingface: StorageHuggingFaceBase | None = Field(
        None, examples=[{"dataset_id": "hirundo-io/bdd100k-validation-only"}, None]
    )
    name: str = Field(..., max_length=255, min_length=1, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    replace_if_exists: bool = Field(False, title="Replace If Exists")
    s3: StorageS3Base | None = Field(
        None,
        examples=[
            {
                "access_key_id": "my-access-key",
                "bucket_url": "s3://my-bucket",
                "region_name": "us-west-2",
                "secret_access_key": "REDACTED",
            },
            None,
        ],
    )
    type: StorageTypes


class CreateUserAssociation(BaseModel):
    organization_id: int = Field(..., examples=[1], title="Organization Id")
    role: Role | None = Field(..., examples=["user"])
    username: str = Field(..., examples=["ben@hirundo.io"], title="Username")


class CustomBehavior(BaseModel):
    biased_dataset: HirundoCSVDataset | HuggingFaceDataset = Field(
        ..., title="Biased Dataset"
    )
    type: Literal["CUSTOM"] = Field("CUSTOM", title="Type")
    unbiased_dataset: HirundoCSVDataset | HuggingFaceDataset = Field(
        ..., title="Unbiased Dataset"
    )


class CustomUtility(BaseModel):
    dataset: HirundoCSVDataset | HuggingFaceDataset = Field(..., title="Dataset")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class HuggingFaceTransformersModel(BaseModel):
    code_revision: str | None = Field(None, title="Code Revision")
    model_name: str = Field(..., title="Model Name")
    revision: str | None = Field(None, title="Revision")
    token: str | None = Field(None, title="Token")
    token_id: int | None = Field(None, title="Token Id")
    type: LlmSourceType = LlmSourceType.HUGGINGFACE_TRANSFORMERS


class HuggingFaceTransformersModelOutput(BaseModel):
    model_name: str = Field(..., title="Model Name")
    type: LlmSourceType = LlmSourceType.HUGGINGFACE_TRANSFORMERS


class LlmSources(RootModel[HuggingFaceTransformersModel | LocalTransformersModel]):
    root: HuggingFaceTransformersModel | LocalTransformersModel


class ModelSources(RootModel[PyTorchRawPthModel | TorchVisionModel]):
    root: PyTorchRawPthModel | TorchVisionModel


class ModifyLlm(BaseModel):
    archive_existing_runs: bool = Field(True, title="Archive Existing Runs")
    creator_id: int | None = Field(None, title="Creator Id")
    model_name: str | None = Field(None, title="Model Name")
    model_source: LlmSources | None = None
    organization_id: int | None = Field(None, title="Organization Id")


class ModifyMLModel(BaseModel):
    archive_existing_runs: bool = Field(True, title="Archive Existing Runs")
    class_mapping_json: dict[str, Any] | list[Any] | None = Field(
        None, title="Class Mapping Json"
    )
    class_mapping_url: str | None = Field(None, title="Class Mapping Url")
    creator_id: int | None = Field(None, title="Creator Id")
    data_root_url: str | None = Field(None, title="Data Root Url")
    model_name: str | None = Field(None, title="Model Name")
    model_source: ModelSources | None = None
    organization_id: int | None = Field(None, title="Organization Id")
    storage_config_id: int | None = Field(None, title="Storage Config Id")


class ModifyStorageConfig(BaseModel):
    azure: StorageAzureBase | None = Field(
        None,
        examples=[
            None,
            {
                "account_key": "my-account",
                "account_name": "my-account-name",
                "container": "my-container",
            },
        ],
    )
    gcp: StorageGCPBase | None = None
    git: CreateStorageGit | None = None
    huggingface: StorageHuggingFaceBase | None = None
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    s3: StorageS3Base | None = Field(
        None,
        examples=[
            {
                "access_key_id": "my-access-key",
                "bucket_url": "s3://my-bucket",
                "region_name": "us-west-2",
                "secret_access_key": "REDACTED",
            },
            None,
        ],
    )
    type: StorageTypes | None = None


class MultimodalModalityCSV(BaseModel):
    augmentations: list[str] | None = Field(None, title="Augmentations")
    data_root_url: str | None = Field(None, title="Data Root Url")
    extra_non_feature_cols: list[str] | None = Field(
        None, title="Extra Non Feature Cols"
    )
    feature_cols: list[str] | None = Field(None, title="Feature Cols")
    labeling_info: HirundoCSV
    modality: MultimodalModalityType


class OutputLlm(BaseModel):
    created_at: datetime = Field(..., title="Created At")
    creator_id: int = Field(..., title="Creator Id")
    creator_name: str = Field(..., title="Creator Name")
    id: int = Field(..., title="Id")
    model_name: str = Field(..., title="Model Name")
    model_source: HuggingFaceTransformersModelOutput | LocalTransformersModel = Field(
        ..., title="Model Source"
    )
    organization_id: int = Field(..., title="Organization Id")
    updated_at: datetime = Field(..., title="Updated At")


class PublicCatalogBenchmark(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str = Field(..., title="Category")
    description: str = Field(..., title="Description")
    id: str = Field(..., pattern="^[A-Za-z0-9_]+$", title="Id")
    paper_url: PaperUrl | None = Field(..., title="Paper Url")
    task_version: str = Field(..., pattern="^\\d+-[A-Z]$", title="Task Version")
    tasks: list[PublicCatalogTask] = Field(..., title="Tasks")
    title: str = Field(..., title="Title")


class PublicCatalogResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    benchmarks: list[PublicCatalogBenchmark] = Field(..., title="Benchmarks")
    schema_version: Literal[1] = Field(1, title="Schema Version")
    source: CatalogSource


class ResponseStorageConfig(BaseModel):
    azure: StorageAzureOut | None = None
    created_at: datetime = Field(..., title="Created At")
    creator_id: int = Field(..., title="Creator Id")
    creator_name: str = Field(..., title="Creator Name")
    gcp: StorageGCPOut | None = None
    git: StorageGitOut | None = None
    huggingface: StorageHuggingFaceOut | None = None
    id: int = Field(..., title="Id")
    name: str = Field(..., max_length=255, min_length=1, title="Name")
    organization_name: str = Field(..., title="Organization Name")
    s3: StorageS3Out | None = None
    type: StorageTypes
    updated_at: datetime = Field(..., title="Updated At")


class UnlearningHyperParameters(BaseModel):
    augmentations: list[AugmentationParams] | None = Field(None, title="Augmentations")
    image_size: ImageSize | None = Field(None, title="Image Size")
    trainer: TrainerParams | None = None


class ServerUnlearningLlmModelsRunRunInfo(BaseModel):
    advanced_options: UnlearningLlmAdvancedOptions | None = None
    aggressiveness: Aggressiveness | None = Field(None, title="Aggressiveness")
    model_id: int | None = Field(None, title="Model Id")
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    target_behaviors: list[
        RaceBias
        | NationalityBias
        | GenderBias
        | PhysicalAppearanceBias
        | ReligionBias
        | AgeBias
        | AllBias
        | GeneralHallucinationBehavior
        | MedicalHallucinationBehavior
        | LegalHallucinationBehavior
        | DefenseHallucinationBehavior
        | SecurityBehavior
        | RefusalBehavior
        | CustomBehavior
    ] = Field(..., min_length=0, title="Target Behaviors")
    target_utilities: list[CustomUtility] = Field(
        ..., min_length=0, title="Target Utilities"
    )


class ServerUnlearningModelsModelsRunRunInfo(BaseModel):
    hyperparameters: UnlearningHyperParameters | None = None
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    predict_at_end: list[DatasetSplit] | None = Field(None, title="Predict At End")
    scenario: ScenarioType = ScenarioType.UNSET
    unlearning_task_info: HirundoCSV


class CreateLlm(BaseModel):
    archive_existing_runs: bool = Field(True, title="Archive Existing Runs")
    model_name: str = Field(..., title="Model Name")
    model_source: LlmSources
    organization_id: int | None = Field(None, title="Organization Id")
    replace_if_exists: bool = Field(False, title="Replace If Exists")


class CreateMLModel(BaseModel):
    archive_existing_runs: bool = Field(True, title="Archive Existing Runs")
    class_mapping_json: dict[str, Any] | list[Any] | None = Field(
        None, title="Class Mapping Json"
    )
    class_mapping_url: str | None = Field(None, title="Class Mapping Url")
    data_root_url: str = Field(..., title="Data Root Url")
    model_name: str = Field(..., title="Model Name")
    model_source: ModelSources
    organization_id: int | None = Field(None, title="Organization Id")
    replace_if_exists: bool = Field(False, title="Replace If Exists")
    storage_config_id: int = Field(..., title="Storage Config Id")


class MultimodalHirundoCSV(BaseModel):
    alignment_csv_url: str | None = Field(None, title="Alignment Csv Url")
    modality_csvs: list[MultimodalModalityCSV] = Field(..., title="Modality Csvs")
    type: Literal["MultimodalHirundoCSV"] = Field("MultimodalHirundoCSV", title="Type")


class OutputMLModel(BaseModel):
    class_mapping_json: dict[str, Any] | list[Any] | None = Field(
        None, title="Class Mapping Json"
    )
    class_mapping_url: str | None = Field(..., title="Class Mapping Url")
    created_at: datetime = Field(..., title="Created At")
    creator_id: int = Field(..., title="Creator Id")
    creator_name: str = Field(..., title="Creator Name")
    data_root_url: str = Field(..., title="Data Root Url")
    id: int = Field(..., title="Id")
    model_name: str = Field(..., title="Model Name")
    model_source: ModelSources
    organization_id: int = Field(..., title="Organization Id")
    storage_config: ResponseStorageConfig
    storage_config_id: int = Field(..., title="Storage Config Id")
    updated_at: datetime = Field(..., title="Updated At")


class LabelingInfo(
    RootModel[
        HirundoCSV
        | MultimodalHirundoCSV
        | COCO
        | YOLO
        | HuggingFaceAudio
        | KeylabsObjDetImages
        | KeylabsObjDetVideo
        | KeylabsObjSegImages
        | KeylabsObjSegVideo
    ]
):
    root: (
        HirundoCSV
        | MultimodalHirundoCSV
        | COCO
        | YOLO
        | HuggingFaceAudio
        | KeylabsObjDetImages
        | KeylabsObjDetVideo
        | KeylabsObjSegImages
        | KeylabsObjSegVideo
    ) = Field(..., discriminator="type")


class CreateDataQADataset(BaseModel):
    augmentations: list[ImageAugmentationName] | list[TabAugmentationName] | None = (
        Field(None, title="Augmentations")
    )
    classes: list[str] | None = Field(None, title="Classes")
    data_root_url: str | None = Field(None, title="Data Root Url")
    extra_non_feature_cols: list[str] | None = Field(
        None, title="Extra Non Feature Cols"
    )
    feature_cols: list[str] | None = Field(None, title="Feature Cols")
    labeling_info: (
        HirundoCSV
        | MultimodalHirundoCSV
        | COCO
        | YOLO
        | HuggingFaceAudio
        | KeylabsObjDetImages
        | KeylabsObjDetVideo
        | KeylabsObjSegImages
        | KeylabsObjSegVideo
        | list[LabelingInfo]
    ) = Field(..., title="Labeling Info")
    labeling_type: LabelingType
    language: str | None = Field(None, title="Language")
    modality: ModalityType = ModalityType.VISION
    name: str = Field(..., title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    replace_if_exists: bool = Field(False, title="Replace If Exists")
    storage_config_id: int = Field(..., title="Storage Config Id")


class DataQADatasetOut(BaseModel):
    augmentations: list[AugmentationName] | None = Field(..., title="Augmentations")
    classes: list[str] | None = Field(..., title="Classes")
    created_at: datetime = Field(..., title="Created At")
    creator_id: int = Field(..., title="Creator Id")
    creator_name: str = Field(..., title="Creator Name")
    data_root_url: str | None = Field(None, title="Data Root Url")
    extra_non_feature_cols: list[str] | None = Field(
        ..., title="Extra Non Feature Cols"
    )
    feature_cols: list[str] | None = Field(..., title="Feature Cols")
    id: int = Field(..., title="Id")
    labeling_info: (
        HirundoCSV
        | MultimodalHirundoCSV
        | COCO
        | YOLO
        | HuggingFaceAudio
        | KeylabsObjDetImages
        | KeylabsObjDetVideo
        | KeylabsObjSegImages
        | KeylabsObjSegVideo
        | list[LabelingInfo]
    ) = Field(..., title="Labeling Info")
    labeling_type: LabelingType
    language: str | None = Field(None, title="Language")
    modality: ModalityType
    name: str = Field(..., title="Name")
    organization_id: int = Field(..., title="Organization Id")
    storage_config: ResponseStorageConfig
    storage_config_id: int = Field(..., title="Storage Config Id")
    updated_at: datetime = Field(..., title="Updated At")


class ModifyDataQADataset(BaseModel):
    augmentations: list[ImageAugmentationName] | list[TabAugmentationName] | None = (
        Field(None, title="Augmentations")
    )
    classes: list[str] | None = Field(None, title="Classes")
    data_root_url: str | None = Field(None, title="Data Root Url")
    extra_non_feature_cols: list[str] | None = Field(
        None, title="Extra Non Feature Cols"
    )
    feature_cols: list[str] | None = Field(None, title="Feature Cols")
    labeling_info: (
        HirundoCSV
        | MultimodalHirundoCSV
        | COCO
        | YOLO
        | HuggingFaceAudio
        | KeylabsObjDetImages
        | KeylabsObjDetVideo
        | KeylabsObjSegImages
        | KeylabsObjSegVideo
        | list[LabelingInfo]
        | None
    ) = Field(None, title="Labeling Info")
    labeling_type: LabelingType | None = None
    language: str | None = Field(None, title="Language")
    modality: ModalityType | None = None
    name: str | None = Field(None, title="Name")
    organization_id: int | None = Field(None, title="Organization Id")
    storage_config: ModifyStorageConfig | None = None
    storage_config_id: int | None = Field(None, title="Storage Config Id")
